GMOOC/ExtraApp/xadmin-master/demo_app/demo/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url

# Uncomment the next two lines to enable the admin:
import xadmin
xadmin.autodiscover()

# version模块自动注册需要版本控制的 Model
from xadmin.plugins import xversion
xversion.register_models()

from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(xadmin.site.urls))
]

GMOOC/GMOOC/urls.py
from django.conf.urls import url,include
from django.contrib import admin
#处理静态文件
from django.views.generic import TemplateView
import xadmin
import crispy_forms
#from users.views import user_login
from users.views import *
from organization.views import OrganiztionListView
from django.views.static import serve
from GMOOC.settings import MEDIA_ROOT,STATICFILES_DIRS
from users.views import IndexView


#错误页面配置
handler403 = permission_denied
handler404 = page_not_found
handler500 = page_error

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    #url(r'^$',TemplateView.as_view(template_name='index.html'),name='index'),
    url(r'^$',IndexView.as_view(),name='index'),
    #传入user_login句柄，指向user_login
    #url(r'^login/$', user_login, name='user_login'),
    url(r'^login/$', LoginView.as_view(), name='user_login'),
    #######################新增注销功能######################
    url(r'^loginout/$', logout_view, name='user_loginout'),
    #########################################################
    url(r'^register/$', RegisterView.as_view(), name='Register'),
    url(r'^captcha/', include('captcha.urls')), #定义图片位置
    #写入注册激活地址，通过url获取激活验证码，注意书写规范
    url(r'^active/(?P<active_code>.*)/$',ActiveUserView.as_view(),name='active_user'),
    url(r'^forgetpwd/$', ForgetpwdView.as_view(), name='forgetpwd'),
    url(r'^password_reset/(?P<active_code>.*)/$', PasswordReset.as_view(), name='password_reset'),
    #####################organization模板复用#######################
    #url(r'organiztion_list/$',OrganiztionListView.as_view(),name='organiztion_list'),
    #url(r'organiztion_list/$', TemplateView.as_view(template_name='org_list.html'), name='organiztion_list'),  #测试

    ######################机构列表##########################################
    url(r'^organization/', include('organization.url',namespace='organization')),  # organiztion 的url分发,namespace用于重名的处理
    ######################课程列表##########################################
    url(r'^courses/', include('courses.url', namespace='courses')), # organiztion 的url分发,namespace用于重名的处理

    ############################################配置动态上传图片资源的访问处理函数#######################################
    url(r'^media/(?P<path>.*)/$', serve, {"document_root":MEDIA_ROOT},name='img_path'),
    #url(r'^static/(?P<path>.*)/$', serve, {"document_root": STATICFILES_DIRS}, name='static_path'),    #直接影响到了静态文件的寻址路径

    ############################################处理机构详情#######################################
    url(r'^forgetpwd/$', ForgetpwdView.as_view(), name='forgetpwd'),

    url(r'^user_center/', include('users.url', namespace='user_info')),# organiztion 的url分发,namespace用于重名的处理

    #富文本相关url
    #url(r'^ueditor/',include('DjangoUeditor.urls' )),
]

'''
user_login和user_login()区别：
user_login代表指向这个函数
user_login()代表调用这个函数
LoginView.as_view():把LoginView类转换为一个as_view,返回一个函数句柄,此处要调用用方法，所以要()。
(?P):提取一个变量当做参数
(?P<active_code>.*):正则表达式.*匹配到的内容填充到<active_code>中
'''

GMOOC/apps/courses/models.py
#_*_ conding:utf-8 _*_
from django.db import models
#auth_user的类
from django.contrib.auth.models import AbstractUser
from datetime import datetime
from organization.models import CourseOrganization,Teacher
#from DjangoUeditor.models import UEditorField

# Create your models here.

class Course(models.Model):
    Organization = models.ForeignKey(CourseOrganization,verbose_name=u'所属机构',null=True,blank=True)
    Describe = models.CharField(verbose_name=u'课程简介',max_length=500)
    CourseName = models.CharField(max_length=100,verbose_name=u'课程名称')
    Detail = models.TextField(verbose_name=u'课程详情')
    #Detail = UEditorField(verbose_name=u'课程详情', width=600, height=300, toolbars="full", imagePath="course/detail/img", filePath="course/detail/file",default='')
    Display = models.BooleanField(default=False,verbose_name=u'展示与否')
    degree = models.CharField(max_length=10,verbose_name=u'课程难度',choices=(('cj',u'初级'),('zj',u'中级'),('gj',u'高级')))
    LearnTime = models.IntegerField(verbose_name=u'学习时长',default=0)
    CourseType = models.CharField(max_length=30,verbose_name=u'课程类型')
    #LearnUser = models.ImageField(upload_to='static/Pic/courses/%Y/%m',max_length=500,verbose_name=u'学习用户')
    CoursePicture = models.ImageField(upload_to='courses/%Y/%m',max_length=500,verbose_name=u'课程封面')
    Students = models.IntegerField(default=0,verbose_name=u'学习人数')
    FavouriteNumber = models.IntegerField(default=0,verbose_name=u'喜欢人数')
    ClikeNumber = models.IntegerField(default=0,verbose_name=u'点击人数')
    AddTime = models.DateTimeField(default=datetime.now,verbose_name=u'添加时间',)
    Tag = models.CharField(default='',max_length=10,verbose_name=u'标签',null=True,blank=True)
    Teacher = models.ForeignKey(Teacher,verbose_name=u'课程老师',null=True,blank=True)
    YouNeedKonw = models.CharField(default='',max_length=300,verbose_name=u'课程须知',null=True,blank=True)
    TeacherTellYou = models.CharField(default='',max_length=300,verbose_name=u'老师告诉你的',null=True,blank=True)

    def __str__(self):
        return '{0}'.format(self.CourseName)

    def get_lesson_nums(self):
        """
        course作为lesson的外键，利用self.lesson_set获取lesson参数
        """
        lesson_num = self.lesson_set.all().count()
        return lesson_num

    def get_study_user(self):
        study_user = self.usercourse_set.all()[:5]
        return study_user

    class Meta:
        verbose_name = u'课程'
        verbose_name_plural = verbose_name


class Lesson(models.Model):
    LessonName = models.CharField(max_length=100,verbose_name=u'章节名称',default='未命名',null=True,blank=True)
    Course = models.ForeignKey(Course,verbose_name=u'课程名称')
    AddTime = models.DateTimeField(default=datetime.now,verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'章节'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '{0}'.format(self.LessonName)

    #获取各个章节下的课程video
    def get_video(self):
        video = self.video_set.all()
        return video

class Video(models.Model):
    LessonName = models.ForeignKey(Lesson,verbose_name=u'章节名称',default='未命名',)
    VideoName = models.CharField(max_length=100, verbose_name=u'视频名称')
    AddTime = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')
    VideoUrl = models.CharField(default='',verbose_name='播放路径',max_length=200,null=True,blank=True) #播放地址
    LearnTime = models.IntegerField(verbose_name=u'学习时长',default=0)

    class Meta:
        verbose_name = u'视频'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '{0}'.format(self.VideoName)



class CourseResource(models.Model):
    Course = models.ForeignKey(Course, verbose_name=u'课程')
    Name = models.CharField(max_length=100, verbose_name=u'名称')
    DownLoad = models.FileField(upload_to='course/resource/%Y/%m/%d',max_length=100, verbose_name=u'下载')
    AddTime = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'课程资源'
        verbose_name_plural = verbose_name

GMOOC/templates/active_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>连接失效！！！</p>
</body>
</html>

GMOOC/templates/course_list.html
{% extends 'organization_base.html' %}
{% load staticfiles %}
{% block title %}课程列表页{% endblock %}
{% block custom_bread %}
        <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li>公开课</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block content %}
    <section>
	<div class="wp">
		<div class="list" style="margin-top:0;">
			<div class="left layout">
				<div class="head">
					<ul class="tab_header">
						<li class="{% ifequal sort 'last' %}active{% endifequal %}"><a href="?sort=last">最新 </a></li>
						<li class="{% ifequal sort 'hot' %}active{% endifequal %}"><a href="?sort=hot">最热门</a></li>
						<li class="{% ifequal sort 'students' %}active{% endifequal %}"><a href="?sort=students">参与人数</a></li>
					</ul>
				</div>
                <div id="inWindow">
                    <div class="tab_cont " id="content">
					<div class="group_list">
                            {% for course in all_course.object_list %}
                            <div class="box">
                                <a href="{% url 'courses:course_detail' course.id %}">
                                    <img width="280" height="350" class="scrollLoading" src="{{ MEDIA_URL }}{{ course.CoursePicture }}"/>
                                </a>
                                <div class="des">
                                    <a href="course_detail.html">
                                        <h2>{{ course.CourseName }}</h2>
                                    </a>
                                    <span class="fl">时长：<i class="key">{{ course.LearnTime }}</i></span>
                                    <span class="fr">学习人数：{{ course.Students }}&nbsp;&nbsp;</span>
                                </div>
                                <div class="bottom">
                                    <a href="course_detail.html"><span class="fl">{{ course.Organization.Organization }}</span></a>
                                    <span class="star fr  notlogin
                                        " data-favid="15">
                                        {{ course.FavouriteNumber }}
                                    </span>
                                </div>
                            </div>
                            {% endfor %}
					</div>


                    {# 页码 #}
                    <div class="pageturn">
                                <ul class="pagelist">

                                    {% if all_course.has_previous %}       {# 判断是否有前一页逻辑 #}
                                    <li class="long"><a href="?{{ all_course.previous_page_number.querystring }}" >上一页</a></li>
                                    {% endif %}

                                        {% for page in all_course.pages %}
                                            {% if page %}
                                                {% ifequal page all_course.number %}  {# 判断是否是当前页 #}
                                                    <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                                                {% else %}  {# 如果不是当前页的话 #}
                    {#                                {% if page %}  {# 如果该页码距离当前页距离为3的话，显示为3个点 #}
                    {#                                    <li class="none"><a href="" class="page">...</a></li>#}
                    {#                                {% else %}#}
                                                        <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                    {#                                {% endif %}#}
                                                {% endifequal %}
                                            {% endif %}
                                        {% endfor %}

                                {% if all_course.has_next %}  {# 判断是否有后一页逻辑 #}
                                    <li class="long"><a href="?{{ all_course.next_page_number.querystring }}">下一页</a></li>
                                {% endif %}

                                </ul>
                            </div>



				</div>
                </div>
			</div>
			<div class="right layout">
				<div class="head">热门课程推荐</div>
				<div class="group_recommend">
                    {% for course in hot_course  %}
                    <dl>
						<dt>
							<a target="_blank" href="">
								<img width="240" height="220" class="scrollLoading" src="{{ MEDIA_URL }}{{ course.CoursePicture }}"/>
							</a>
						</dt>
						<dd>
							<a target="_blank" href=""><h2> {{ course.CourseName }}</h2></a>
                            {# 利用get_model_display用于显示choice的选项代表值 #}
							<span class="fl">难度：<i class="key">{{ course.get_degree_display }}</i></span>
						</dd>

					</dl>
                    {% endfor %}

				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

GMOOC/templates/course_video.html
{% extends 'organization_base.html' %}
{% load staticfiles %}
{% block title %}课程详情{% endblock %}
{% block custom_bread %}
        <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'courses:courses_list' %}">公开课程</a>></li>
                <li><a href="{% url 'courses:course_detail' course.id %}">课程详情</a>></li>
                <li>章节信息</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block customcss %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/base.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/common-less.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/learn-less.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/aui.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}" />
     <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/common-less.css' %}">
{% endblock %}

{% block header %}
<section class="headerwrap ">
    <header>
		<div  class=" header">
 			<!--<div class="top">
				<div class="wp">
					<div class="fl"><p>服务电话：<b>33333333</b></p></div>
                        <a style="color:white" class="fr registerbtn" href="register.html">注册</a>
                        <a style="color:white" class="fr loginbtn" href="login.html">登录</a>
				</div>
			</div>-->

            {% if request.user.is_authenticated %}
                <div class="top">
				<div class="wp">
					<div class="fl">
						<p>服务电话：<b>33333333</b></p>
                    </div>
					    <!--登录后跳转-->

						<div class="personal">
                            <dl class="user fr">
                                <dd>{{ user.username }}<img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                                <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ user.img }}"/></dt>
                            </dl>
                            <div class="userdetail">
                            	<dl>
	                                <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ user.img }}"/></dt>
	                                <dd>
	                                    <h2>{{ user.gender }}</h2>
	                                    <p>{{ user.username }}</p>
	                                </dd>
                                </dl>
                                <div class="btn">
	                                <a class="personcenter fl" href="usercenter_info.html">进入个人中心</a>
	                                <a class="fr" href="{% url 'user_loginout' %}?next={{ request.path }}">退出</a>
                                </div>
                            </div>
                        </div>
                    </div>
			</div>
                {% else %}
                <div class="top">
                        <div class="wp">
                            <div class="fl">
                                <p>服务电话：<b>33333333</b></p></div>
                            <a style="color:white" class="fr registerbtn" href="{% url 'Register' %}">注册</a>
                            <a style="color:white" class="fr loginbtn" href="{% url 'user_login' %}?next={{ request.path }}">登录</a>
                        </div>
                    </div>
            {% endif %}

            <div class="middle">
                <div class="wp">
                    <a href="index.html"><img class="fl" src="{% static 'images/logo.jpg' %}"/></a>
                    <div class="searchbox fr">
                        <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" data-value="course">
                                公开课
                            </span>
                            <ul class="selectMenu" id="jsSelectMenu">
                                <li data-value="course">公开课</li>
                                <li data-value="org">课程机构</li>
                                <li data-value="teacher">授课老师</li>
                            </ul>
                        </div>
                        <input id="search_keywords" class="fl" type="text" value="" placeholder="请输入搜索内容"/>
                        <img class="search_btn fr" id="jsSearchBtn" src="{% static 'images/search_btn.png' %}"/>
                    </div>
                </div>
            </div>


			<nav>
				<div class="nav">
					<div class="wp">
						<ul>
							<li ><a href="{% url 'index' %}">首页</a></li>
							<li class="active">
								<a href="{% url 'courses:courses_list' %}">
									公开课<img class="hot" src="{% static 'images/nav_hot.png' %}">
								</a>
							</li>
							<li >
								<a href="teachers_list.html">授课教师</a>
							</li>
							<li class="" ><a href="{% url 'organization:organiztion_list' %}">授课机构</a></li>
						</ul>
					</div>
				</div>
			</nav>

			</div>
    </header>
</section>
{% endblock %}


<!--crumbs start-->
{% block content %}
    <div id="main">
        {# 课程信息 #}
    <div class="course-infos">
        <div class="w pr">
            <div style="height: 15px" class="path">
            </div>
            <div class="hd">
                <h2 class="l">   {{ course.CourseName }}</h2>
            </div>
            <div class="statics clearfix">
                <div class="static-item ">
                    <span class="meta-value"><strong>{{ course.get_degree_display }}</strong></span>
                    <span class="meta">难度</span>
                    <em></em>
                </div>
                <div class="static-item static-time">
                    <span class="meta-value"><strong>{{ course.LearnTime }}</strong></span>
                    <span class="meta">时长</span>
                    <em></em>
                </div>
                <div class="static-item">
                    <span class="meta-value"><strong>{{ course.Students }}</strong></span>
                    <span class="meta">学习人数</span>
                    <em></em>
                </div>
            </div>
        </div>
    </div>
        {# 具体内容 #}
    <div class="course-info-main clearfix w has-progress">
        <div class="info-bar clearfix">
        <div class="content-wrap clearfix">
            {# 章节主要内容 #}
            <div class="content">
                <div class="mod-tab-menu">
                    <ul class="course-menu clearfix">
                        <li><a class="ui-tabs-active active" id="learnOn"  href="{% url 'courses:course_video' course.id %}"><span>章节</span></a></li>
                        <li><a id="commentOn" class="" href="{% url 'courses:courses_comment' course.id %}"><span>评论</span></a></li>
                    </ul>
                </div>
                <div id="notice" class="clearfix">
                    <div class="l"> <strong>课程公告:</strong> <a  href="javascript:void(0)">Spring的文档以及相关的jar文件已上传</a> </div>
                </div>

                {# 章节内容 #}
                <div class="mod-chapters">
                    
                    <div class="chapter chapter-active" >
                        {% for l in lesson %}
                        <h3>
                            <strong><i class="state-expand"></i>{{ l.LessonName }}</strong>
                        </h3>
                            <ul class="video">
                                {% for v in l.get_video %}
                                    <li>
                                        <a target="_blank" href='{% url "courses:video_play" v.id %}' class="J-media-item studyvideo">{{ v.VideoName }}({{ v.LearnTime }}:00)
                                            <i class="study-state"></i>
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>
                        {% endfor %}
                    </div>
                    
                </div>

                </div>
            {# 右边资料 #}
            <div class="aside r">
                <div class="bd">
                    <div class="box mb40">
                        <h4>资料下载</h4>
                        <ul class="downlist">
                            {% for resource in course_resource %}
                            <li>
                                <span ><i class="aui-iconfont aui-icon-file"></i>{{ resource.Name }}</span>
                                <a href="{{ MEDIA_URL }}{{ resource.DownLoad }}" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="box mb40">
                        <h4>讲师提示</h4>
                        <div class="teacher-info">
                            <a href="/u/315464/courses?sort=publish" target="_blank">
                                <img src='{{ MEDIA_URL }}{{ course.Teacher.TeacherImage }}' width='80' height='80' />
                            </a>
        <span class="tit">
          <a href="{{ MEDIA_URL }}{{ course.Teacher.TeacherImage }}" target="_blank">{{ course.Teacher.TeacherName }}</a>
        </span>
                            <span class="job">{{ course.Teacher.WorkPosition }}</span>
                        </div>
                        <div class="course-info-tip">
                            <dl class="first">
                                <dt>课程须知</dt>
                                <dd class="autowrap">{{ course.YouNeedKonw }}</dd>
                            </dl>
                            <dl>
                                <dt>老师告诉你能学到什么？</dt>
                                <dd class="autowrap">{{ course.TeacherTellYou }}</dd>
                            </dl>
                        </div>
                    </div>
                    <div class="cp-other-learned  js-comp-tabs">
                        <div class="cp-header clearfix">
                            <h2 class="cp-tit l">该课的同学还学过</h2>
                        </div>
                        <div class="cp-body">
                            <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                                <!-- img 200 x 112 -->
                                <ul class="other-list">
                                    {% for Cours in Related_Courses %}
                                        <li class="curr">
                                            <a href="{% url 'courses:course_detail' Cours.Course.id %}" target="_blank">
                                            <img src="" alt="{{ Cours.Course.CourseName }}">
                                            <span class="name autowrap">{{ Cours.Course.CourseName }}</span>
                                        </a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                            <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="plan">
                                <ul class="other-list">
                                    <li class="curr">
                                        <a href="/course/programdetail/pid/31?src=sug" target="_blank">
                                            <img src="http://img.mukewang.com/56551e6700018b0c09600720-240-135.jpg" alt="Java工程师">
                                            <span class="name autowrap">Java工程师</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div class="clear"></div>

    </div>

</div>
    </div>
{% endblock %}

GMOOC/templates/login.html
<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>慕学在线网登录</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/login.css">
</head>
<body>
<div class="dialog" id="jsDialog">
<!--提示弹出框-->
<div class="successbox dialogbox" id="jsSuccessTips">
    <h1>成功提交</h1>
    <div class="close jsCloseDialog"><img src="/static/images/dig_close.png"/></div>
    <div class="cont">
        <h2>您的需求提交成功！</h2>
        <p></p>
    </div>
</div>
<div  class="noactivebox dialogbox" id="jsUnactiveForm" >
    <h1>邮件验证提示</h1>
    <div class="close jsCloseDialog"><img src="/static/images/dig_close.png"/></div>
    <div class="center">
        <img src="/static/images/send.png"/>
        <p>我们已经向您的邮箱<span class="green" id="jsEmailToActive">12@13.com</span>发送了邮件，<br/>为保证您的账号安全，请及时验证邮箱</p>
        <p class="a"><a class="btn" id="jsGoToEmail" target="_blank" href="http://mail.qq.com">去邮箱验证</a></p>
        <p class="zy_success upmove"></p>
        <p style="display: none;" class="sendE2">没收到，您可以查看您的垃圾邮件和被过滤邮件，也可以再次发送验证邮件（<span class="c5c">60s</span>）</p>
        <p class="sendE">没收到，您可以查看您的垃圾邮件和被过滤邮件，<br/>也可以<span class="c5c green" id="jsSenEmailAgin" style="cursor: pointer;">再次发送验证邮件</span></p>
    </div>
</div>
</div>
<div class="bg" id="dialogBg"></div>
<header>
    <div class="c-box fff-box">
        <div class="wp header-box">
            <p class="fl hd-tips">慕学在线网，在线学习平台！</p>
            <ul class="fr hd-bar">
                <li>服务电话：<span>33333333</span></li>
                <li class="active"><a href="login.html">[登录]</a></li>
                <li><a href="register.html">[注册]</a></li>
            </ul>
        </div>
    </div>
</header>
<section>
    <div class="c-box bg-box">
        <div class="login-box clearfix">
            <div class="hd-login clearfix">
                <a class="index-logo" href="index.html"></a>
                <h1>用户登录</h1>
                <a class="index-font" href="index.html">回到首页</a>
            </div>
            <div class="fl slide">
                <div class="imgslide">
                    <ul class="imgs">
                            <li><a href=""><img width="483" height="472" src="/static/images/mysql.jpg" /></a></li>
                            <li><a href=""><img width="483" height="472" src="/static/images/mysql.jpg" /></a></li>
                            <li><a href=""><img width="483" height="472" src="/static/images/mysql.jpg" /></a></li>
                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>
            <div class="fl form-box">
                <h2>帐号登录</h2>

                <form action="/login/" method="post" autocomplete="off">
                    <input type='hidden' name='csrfmiddlewaretoken' value='mymQDzHWl2REXIfPMg2mJaLqDfaS1sD5' />
                    <div class="form-group marb20 {% if login_form.errors.username %}errorput{% endif %}">
                        <label>用&nbsp;户&nbsp;名</label>
                        <input name="username" id="account_l" value="{{ login_form.username.value }}" type="text" placeholder="手机号/邮箱" />
                    </div>
                    <div class="form-group marb8 {% if login_form.errors.password %}errorput{% endif %}">
                        <label>密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</label>
                        <input name="password" id="password_l" type="password" value="{{ login_form.password.value }}" placeholder="请输入您的密码" />
                    </div>
                    <div class="error btns login-form-tips" id="jsLoginTips">{% for key,error in login_form.errors.items %}{{ error }}{% endfor %}{{ msg }}</div>
                     <div class="auto-box marb38">

                        <a class="fr" href="{% url 'forgetpwd' %}">忘记密码？</a>
                     </div>
                     <input  class="btn btn-green" id="jsLoginBtn" type="submit" value="立即登录 > " />
                <input type="hidden" name="next_page" value="{{ next_page }}">{# 用于给POST函数获取来也页面字段 #}
                <input type='hidden' name='csrfmiddlewaretoken' value='5I2SlleZJOMUX9QbwYLUIAOshdrdpRcy' />
                    {% csrf_token %}
                </form>
                <p class="form-p">没有慕学在线网帐号？<a href="register.html">[立即注册]</a></p>
            </div>
        </div>
    </div>
</section>
<script src="/static/js/jquery.min.js" type="text/javascript"></script>
<script src="/static/js/unslider.js" type="text/javascript"></script>
<script src="/static/js/login.js"  type="text/javascript"></script>
</body>
</html>

GMOOC/templates/password_reset.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	<title>密码修改</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

<body>
<div class="wp">
    <div class="resetpassword" id="resetPwdForm">
        <h1>修改密码</h1>
        <p>已经通过验证，请设置新密码</p>
        <form id="reset_password_form" action="" method="post">
            <ul>
                <li>
                    <span class="">新 密 码 ：</span>
                    <input type="password" name="password" id="pwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <li>
                    <span class="">确定密码：</span>
                    <input type="password" name="password2" id="repwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <div class="error btns" id="jsEmailTips">{{ msg }}</div>
                <li class="button">
                    <!--<input type="button" value="提交" onclick="reset_password_form_submit()">-->
                    <input class="btn btn-green" id="jsEmailRegBtn" type="submit" value="注册并登录" style="background:green;color:white"/>

                </li>
            </ul>
            {% csrf_token %}
        </form>
    </div>
    <div class="resetpassword" id="reset_password_tips" style="display:none;">
        <h1>修改密码成功,请重新登录</h1>
        <img class="fl" src="{% static 'images/check2.png' %}">
        <p class="successword">已经成功修改密码，请重新登录</p>
    </div>
</div>
</body>
</html>

GMOOC/templates/send_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>邮件已发送成功！</p>
<div>
    <a class="index-logo" href="{% url 'user_login' %}">点击重定向至login页面</a>
</div>
</body>
</html>